#!/usr/bin/env bash
set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-${HOME}/.local/bin}"
CONFIG_PATH="${CONFIG_PATH:-${HOME}/.mediacleanup.conf}"
DEFAULT_MEDIA_DIR="${DEFAULT_MEDIA_DIR:-${HOME}/Movies/NewMedia}"
ALLOWED_EXT="${ALLOWED_EXT:-mp4 mkv avi mov flv wmv mpg mpeg webm m4v srt DS_Store}"
SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT_SOURCE="$SCRIPT_ROOT/mediacleanup.sh"
INSTALL_TARGET="$INSTALL_DIR/mediacleanup"

trap 'echo "Install cancelled."; exit 130' INT

sanitize_value() {
  local text="$1"
  text="${text//$'\r'/}"
  text="${text//$'\n'/}"
  text="${text//$'\x1b'/}"
  printf '%s' "$text"
}

prompt_input() {
  local prompt_line="$1"
  local input
  printf '%s' "$prompt_line" >&2
  if ! IFS= read -r input; then
    echo >&2
    exit 1
  fi
  input="$(sanitize_value "$input")"
  printf '\033[1A\033[2K' >&2
  printf '%s%s\n' "$prompt_line" "$input" >&2
  printf '%s\n' "$input"
}

main() {
  local dirs=()
  local prompt_msg="Add a media directory (leave blank to finish; default: ${DEFAULT_MEDIA_DIR}): "
  local google_account=""
  local use_google=0
  local prompt_conf="Config already exists at $CONFIG_PATH. Overwrite? [y/N]: "

  local skip_config_write=0
  if [[ -f "$CONFIG_PATH" ]]; then
    local answer
    answer="$(prompt_input "$prompt_conf")"
    case "${answer,,}" in
      y|yes)
        ;;
      *)
        skip_config_write=1
        echo "Existing config at $CONFIG_PATH will not be overwritten."
        ;;
    esac
  fi

  local confirm_msg="Install mediacleanup to $INSTALL_TARGET? [Y/n]: "
  local confirm_answer
  confirm_answer="$(prompt_input "$confirm_msg")"
  case "${confirm_answer,,}" in
    n|no)
      echo "Installation cancelled."
      exit 0
      ;;
    *)
      ;;
  esac

  if [[ $skip_config_write -eq 0 ]]; then
    local google_prompt="Use Google Drive? [y/N]: "
    local google_email
    google_email="$(prompt_input "$google_prompt")"
    case "${google_email,,}" in
      y|yes)
        use_google=1
        while [[ -z "$google_account" ]]; do
          google_account="$(prompt_input "Google account email (required): ")"
        done
        ;;
      *)
        use_google=0
        ;;
    esac
  fi

  if [[ $skip_config_write -eq 0 ]]; then
    while true; do
      local entry
      entry="$(prompt_input "$prompt_msg")"
      if [[ -z "$entry" ]]; then
        if [[ ${#dirs[@]} -eq 0 ]]; then
          dirs=("$DEFAULT_MEDIA_DIR")
        fi
        break
      fi
      dirs+=("$entry")
    done
  fi

  if [[ $skip_config_write -eq 0 ]]; then
    for dir in "${dirs[@]}"; do
      mkdir -p "$dir"
    done
  fi
  mkdir -p "$INSTALL_DIR"
  if ! install -Dm755 "$SCRIPT_SOURCE" "$INSTALL_TARGET"; then
    echo "Failed to write $INSTALL_TARGET (permission denied)."
    echo "Re-run with sudo or set INSTALL_DIR to a writable location before retrying."
    exit 1
  fi
  echo "Installed mediacleanup to $INSTALL_TARGET"

  local allowed_bits
  read -r -a allowed_bits <<< "$ALLOWED_EXT"

  if [[ $skip_config_write -ne 1 ]]; then
    {
      printf '# Generated by make install (%s)\n' "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      if [[ $use_google -eq 1 ]]; then
        printf 'GOOGLE_ACCOUNT="%s"\n' "$google_account"
        printf "GOOGLE_DRIVE_ROOT=\"\\\${HOME}/Library/CloudStorage\"\n"
      printf 'GOOGLE_DRIVE_PATH="GoogleDrive-%s/My Drive/Media"\n' "$google_account"
        printf "GOOGLE_DRIVE_BASE=\"\\\${GOOGLE_DRIVE_ROOT}/\\\${GOOGLE_DRIVE_PATH}\"\n"
    else
      printf '%s\n' '# GOOGLE_ACCOUNT="<you>@example.com"'
        printf "# GOOGLE_DRIVE_ROOT=\"\\\${HOME}/Library/CloudStorage\"\n"
      printf '%s\n' '# GOOGLE_DRIVE_PATH="GoogleDrive-<you>@example.com/My Drive/Media"'
        printf "# GOOGLE_DRIVE_BASE=\"\\\${GOOGLE_DRIVE_ROOT}/\\\${GOOGLE_DRIVE_PATH}\"\n"
      fi
      printf 'MEDIA_DIRS=(\n'
      for dir in "${dirs[@]}"; do
        printf '  "%s"\n' "$dir"
      done
      printf ')\n'
      printf 'ALLOWED_FILE_EXT=(\n'
      for ext in "${allowed_bits[@]}"; do
        printf '  "%s"\n' "$ext"
      done
      printf ')\n'
    } > "$CONFIG_PATH"
    echo "Config written to $CONFIG_PATH"
  fi
}

main
