#!/usr/bin/env bash
set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"
CONFIG_PATH="${CONFIG_PATH:-${HOME}/.mediacleanup.conf}"
DEFAULT_MEDIA_DIR="${DEFAULT_MEDIA_DIR:-${HOME}/Movies/NewMedia}"
ALLOWED_EXT="${ALLOWED_EXT:-mp4 mkv avi mov flv wmv mpg mpeg webm m4v srt DS_Store}"
SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT_SOURCE="$SCRIPT_ROOT/mediacleanup.sh"
INSTALL_TARGET="$INSTALL_DIR/mediacleanup.sh"

trap 'echo "Install cancelled."; exit 130' INT

sanitize_value() {
  local text="$1"
  text="${text//$'\r'/}"
  text="${text//$'\n'/}"
  text="${text//$'\x1b'/}"
  printf '%s' "$text"
}

prompt_input() {
  local prompt_line="$1"
  local input
  printf '%s' "$prompt_line" >&2
  if ! IFS= read -r input; then
    echo >&2
    exit 1
  fi
  input="$(sanitize_value "$input")"
  printf '\033[1A\033[2K' >&2
  printf '%s%s\n' "$prompt_line" "$input" >&2
  printf '%s\n' "$input"
}

main() {
  local dirs=()
  local prompt_msg="Add a media directory (leave blank to finish; default: ${DEFAULT_MEDIA_DIR}): "

  while true; do
    local entry
    entry="$(prompt_input "$prompt_msg")"
    if [[ -z "$entry" ]]; then
      if [[ ${#dirs[@]} -eq 0 ]]; then
        dirs=("$DEFAULT_MEDIA_DIR")
      fi
      break
    fi
    dirs+=("$entry")
  done

  for dir in "${dirs[@]}"; do
    mkdir -p "$dir"
  done
  mkdir -p "$INSTALL_DIR"
  if ! install -Dm755 "$SCRIPT_SOURCE" "$INSTALL_TARGET"; then
    echo "Failed to write $INSTALL_TARGET (permission denied)."
    echo "Re-run with sudo or set INSTALL_DIR to a writable location before retrying."
    exit 1
  fi

  local overwrite=1
  if [[ -f "$CONFIG_PATH" ]]; then
    overwrite=0
    local answer
    local prompt_conf="Config already exists at $CONFIG_PATH. Overwrite? [y/N]: "
    answer="$(prompt_input "$prompt_conf")"
    case "${answer,,}" in
      y|yes)
        overwrite=1
        ;;
      *)
        overwrite=0
        ;;
    esac
  fi

  local allowed_bits
  read -r -a allowed_bits <<< "$ALLOWED_EXT"

  if [[ $overwrite -eq 1 ]]; then
    {
      printf '# Generated by make install (%s)\n' "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      printf 'MEDIA_DIRS=(\n'
      for dir in "${dirs[@]}"; do
        printf '  "%s"\n' "$dir"
      done
      printf ')\n'
      printf 'ALLOWED_FILE_EXT=(\n'
      for ext in "${allowed_bits[@]}"; do
        printf '  "%s"\n' "$ext"
      done
      printf ')\n'
    } > "$CONFIG_PATH"
    echo "Config written to $CONFIG_PATH"
  else
    echo "Left existing config at $CONFIG_PATH untouched."
  fi
}

main
