#!/usr/bin/env python3
"""Interactive installer for mediacleanup."""

from __future__ import annotations

import datetime as dt
import os
import shutil
import signal
import stat
from pathlib import Path

INSTALL_DIR = Path(os.environ.get("INSTALL_DIR", str(Path.home() / ".local/bin"))).expanduser()
CONFIG_PATH = Path(os.environ.get("CONFIG_PATH", str(Path.home() / ".mediacleanup.toml"))).expanduser()
DEFAULT_MEDIA_DIR = Path(os.environ.get("DEFAULT_MEDIA_DIR", str(Path.home() / "Movies/NewMedia"))).expanduser()
GOOGLE_DRIVE_ROOT = Path.home() / "Library" / "CloudStorage"
GOOGLE_DRIVE_MEDIA_SUBPATH = "My Drive/Media"
ALLOWED_EXT = os.environ.get(
    "ALLOWED_EXT",
    "mp4 mkv avi mov flv wmv mpg mpeg webm m4v srt DS_Store",
).split()
SCRIPT_ROOT = Path(__file__).resolve().parent.parent
SCRIPT_SOURCE = SCRIPT_ROOT / "src" / "mediacleanup.py"
INSTALL_TARGET = INSTALL_DIR / "mediacleanup"


def on_interrupt(_signum: int, _frame: object) -> None:
    print("Install cancelled.")
    raise SystemExit(130)


def prompt(label: str) -> str:
    print(label, end="", flush=True)
    return input().strip().replace("\x1b", "")


def write_config(path: Path, media_dirs: list[Path], allowed_ext: list[str]) -> None:
    lines: list[str] = [
        f"# Generated by make install ({dt.datetime.now(dt.UTC).isoformat()})",
        "",
    ]

    lines.append("media_dirs = [")
    for d in media_dirs:
        lines.append(f'  "{d}",')
    lines.append("]")
    lines.append("")
    lines.append("allowed_file_ext = [")
    for ext in allowed_ext:
        lines.append(f'  "{ext}",')
    lines.append("]")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def install_binary() -> None:
    INSTALL_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copy2(SCRIPT_SOURCE, INSTALL_TARGET)
    mode = stat.S_IMODE(INSTALL_TARGET.stat().st_mode)
    INSTALL_TARGET.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def main() -> int:
    signal.signal(signal.SIGINT, on_interrupt)

    overwrite = True
    if CONFIG_PATH.exists():
        answer = prompt(f"Config already exists at {CONFIG_PATH}. Overwrite? [y/N]: ").lower()
        if answer not in {"y", "yes"}:
            overwrite = False
            print(f"Existing config at {CONFIG_PATH} will not be overwritten.")

    confirm = prompt(f"Install mediacleanup to {INSTALL_TARGET}? [Y/n]: ").lower()
    if confirm in {"n", "no"}:
        print("Installation cancelled.")
        return 0

    media_dirs: list[Path] = []
    if overwrite:
        use_google = prompt("Use Google Drive media directories? [y/N]: ").lower() in {"y", "yes"}
        if use_google:
            account = ""
            while not account:
                account = prompt("Google account email (required): ").strip()
            media_subpath = prompt(
                f'Google Drive media subpath [default: "{GOOGLE_DRIVE_MEDIA_SUBPATH}"]: '
            ).strip()
            media_subpath = media_subpath or GOOGLE_DRIVE_MEDIA_SUBPATH
            google_base = GOOGLE_DRIVE_ROOT / f"GoogleDrive-{account}" / media_subpath
            for google_dir in [google_base / "TV Shows", google_base / "Movies"]:
                media_dirs.append(google_dir)
                print(f"Added media directory: {google_dir}")

        while True:
            if use_google:
                entry = prompt("Add another media directory (leave blank to finish): ")
            else:
                entry = prompt(
                    f"Add a media directory (leave blank to finish; default: {DEFAULT_MEDIA_DIR}): "
                )
            if not entry:
                if not use_google and not media_dirs:
                    media_dirs = [DEFAULT_MEDIA_DIR]
                    print(f"Added media directory: {DEFAULT_MEDIA_DIR}")
                break
            chosen = Path(entry).expanduser()
            media_dirs.append(chosen)
            print(f"Added media directory: {chosen}")

        for d in media_dirs:
            d.mkdir(parents=True, exist_ok=True)

    try:
        install_binary()
    except OSError as exc:
        print(f"Failed to write {INSTALL_TARGET} ({exc.strerror or 'filesystem error'}).")
        print("Re-run with sudo or set INSTALL_DIR to a writable location before retrying.")
        return 1

    print(f"Installed mediacleanup to {INSTALL_TARGET}")

    if overwrite:
        write_config(CONFIG_PATH, media_dirs, ALLOWED_EXT)
        print(f"Config written to {CONFIG_PATH}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
